services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook.py
    envVars:
      - key: BOT_TOKEN
        value: 7098191858:AAEOL8NazzqpCh9iJjv-YpkTUFukfEbdFyg